name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/indramhrt/IC-4-Assignment
            git checkout main
            git pull origin main
            sudo docker rmi ic-4:latest
            sudo docker rm ic-4
            sudo docker build -t ic-4:latest .
            sudo docker run -d -p 8000:8000 --name ic-4 ic-4